name: Frontend Deploy

on:
  push:
    branches:
      - main  # Deploy only on main branch pushes (adjust as needed)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Matches backend Node version

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
        env:
          REACT_APP_SERVER_URL: https://video-sharing-app-x6z9.onrender.com  # Replace with backend IP or domain

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: aws s3 sync build/ s3://video-sharing-frontend-deployment --delete